name: Manual Hello World

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select Browser"
        required: true
        type: choice
        default: chromium
        options:
          - chromium
          - firefox
          - webkit

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Show Selected Browser
        run: echo "Selected Browser:${{ inputs.browser }}"

      - name: Print Hello World
        run: echo "Hello World"