name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select Browser"
        required: true
        default: chromium
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Print selected browser
        run: echo "${{ github.event.inputs.browser }}"

      - name: Run sum file
        run: node sum.js